import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import NextAuthProvider from "@/components/NextAuthProvider/NextAuthProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Rick and Morty',
  description: 'Generated by create next app',
}

interface LayoutProps {
    children: React.ReactNode,
    modal: React.ReactNode,
}

export default async function RootLayout({
                                             children, modal
                                         }: LayoutProps) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider>
              {children}
          {modal}
      </NextAuthProvider>
      </body>
    </html>
  )
}
