import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Footer} from "@/app/components/Footer/Footer";
import {Header} from "@/app/components/Header/Header";
import React from "react";
import {INavigationLink} from "@/types/navigationLinks.types";
import {SessionProvider} from "next-auth/react";
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/route";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Rick and Morty',
  description: 'Generated by create next app',
}

const NAVIGATION_LINKS: INavigationLink[] = [
    {title: "Characters", link: '/'},
    {title: "Locations", link: '/locations'}
]

interface LayoutProps {
    children: React.ReactNode,
    modal: React.ReactNode,
}

export default async function RootLayout({
                                             children, modal
                                         }: LayoutProps) {
    const session = await getServerSession(authOptions)

  return (
      <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={session}>
          <Header navigationLinks={NAVIGATION_LINKS}/>
          <main>
              {children}
          </main>
          {modal}
          <Footer/>
      </SessionProvider>
      </body>
    </html>
  )
}
