import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Footer} from "@/components/Footer/Footer";
import {Header} from "@/components/Header/Header";
import React from "react";
import {INavigationLink} from "@/types/navigationLinks.types";
import {NextIntlProvider} from "next-intl";
import {notFound} from "next/navigation";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Rick and Morty',
    description: 'Generated by create next app',
}

const NAVIGATION_LINKS: INavigationLink[] = [
    {title: "Characters", link: '/'},
    {title: "Locations", link: '/locations'}
]

export default async function RootLayout({
                                             children, modal, params: {locale}
                                         }: {
    children: React.ReactNode,
    modal: React.ReactNode,
    params: { locale: string }
}) {
    let messages;
    try {
        messages = (await import(`../../messages/${locale}.json`)).default;
    } catch (error) {
        notFound();
    }

    return (
        <html lang={locale}>
        <body className={inter.className}>
        <NextIntlProvider locale={locale} messages={messages}>
            <Header navigationLinks={NAVIGATION_LINKS}/>
            <main>
                {children}
            </main>
            {modal}
            <Footer/>
        </NextIntlProvider>
        </body>
        </html>
    )
}
